#日志设置
logging:
  level:
    root: debug
  file: jlpati-eureka-client.log
  org:
    springframework:
      web:  DEBUG


spring:
  output:
    ansi:
      enabled: always #logging console 输出颜色设置
  application:
    name: eureka-client-4
server:
  port: 9009
  host: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@${server.host}:8010/eureka/
  instance:
    metadata-map:
      management.port: ${management.port:8081}
turbine:
  aggregator:
    clusterConfig: CUSTOMERS
  appConfig: customers

